/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connectfour.windows;

import connect4.GameLogger;
import connect4.Model;
import connect4.PlayerClass;

/**
 *
 * @author Rob
 */
public class StartScreenJFrame extends javax.swing.JFrame
{

	/**
	 * Creates new form StartScreenJFrame
	 */
	public StartScreenJFrame()
	{
		initComponents();
	}

	//
	//	event handlers
	//
	private void onExitJButtonActionPerformed()
	{
		System.exit(0);
	}
	
	private void onStartJButtonActionPerformed()
	{
	this.setVisible(false);
		GameLogger.getInstance().log("Game is started");
		Model model = new Model.Builder().build();

	
		PlayerClass player = new PlayerClass(model, 1);
		PlayerClass player1 = new PlayerClass(model, 2);
		model.addPlayer(GameLogger.getInstance());
		model.startGame();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        rulesJLabel = new javax.swing.JLabel();
        buttonsJPanel = new javax.swing.JPanel();
        startJButton = new javax.swing.JButton();
        exitJButton = new javax.swing.JButton();
        headingJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connect Four");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        rulesJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rulesJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rulesJLabel.setText("Welcome to Connect Four game");
        rulesJLabel.setToolTipText("");
        getContentPane().add(rulesJLabel);

        buttonsJPanel.setLayout(new java.awt.GridLayout(1, 2));

        startJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        startJButton.setText("Start");
        startJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startJButtonActionPerformed(evt);
            }
        });
        buttonsJPanel.add(startJButton);

        exitJButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitJButton.setText("Exit");
        exitJButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitJButtonActionPerformed(evt);
            }
        });
        buttonsJPanel.add(exitJButton);

        getContentPane().add(buttonsJPanel);

        headingJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        headingJLabel.setText("<html>Instructions<br>1. Press the start button to begin the game. <br>2. Seperate the two screens. <br>3. Begin with player 1 and enter a number between 1 and 7. <br>4. Enjoy!.</html>");
        getContentPane().add(headingJLabel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_startJButtonActionPerformed
    {//GEN-HEADEREND:event_startJButtonActionPerformed
        onStartJButtonActionPerformed();
    }//GEN-LAST:event_startJButtonActionPerformed

    private void exitJButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitJButtonActionPerformed
    {//GEN-HEADEREND:event_exitJButtonActionPerformed
        onExitJButtonActionPerformed();
    }//GEN-LAST:event_exitJButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        onExitJButtonActionPerformed();
    }//GEN-LAST:event_formWindowClosed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsJPanel;
    private javax.swing.JButton exitJButton;
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JLabel rulesJLabel;
    private javax.swing.JButton startJButton;
    // End of variables declaration//GEN-END:variables

	

	
}
